<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html><head>
  <meta content="text/html; charset=UTF-8" http-equiv="content-type">
  <title>Terms &amp; Conditions</title>
  

</head>
<body>
<center>
<table style="font-family: Arial; color: rgb(102, 102, 102); width: 707px; height: 88px; text-align: left; margin-left: auto; margin-right: auto;" cellspacing="10" cellpadding="10" border="0">
  <tbody style="text-align:justify;">
	<tr>
	<td>
	
	<p><strong>Terms &amp; Conditions</strong></p>

<p>Important: After filling out the form on our website you 
will be contacted by phone, email or both by Debt Advisors and/or 
 up to three of our debt partners for a free debt consultation. The purpose of your 
consultation will be to help determine if you qualify for a debt 
relief program, provide you with information and answer any 
questions you may have. Additionally, you may be added to the Debt Advisors 
email newsletter and that of our debt partners. These newsletters will contain information, 
tips and advice to help you become debt free as well as special promotions related to the same. 
You may withdraw your consent to receive email from Debt Advisors by clicking the "unsubscribe" 
link located at the bottom of every email or emailing support@debtadvisors22.ca with your request 
to be removed from our list. You may also withdraw your consent to receive email from each of our 
debt partners individually by clicking the "unsubscribe" link in their emails or by responding
to any email received requesting to be removed from their list.
</p>
<p>You  are under no obligation to make a purchase
 by taking part in a free consultation. If you qualify for and choose 
to participate in a debt relief program, your individual results 
may vary. Settlement  estimates of 50 - 75% are examples of past 
performance and are not   intended to be a guarantee of future 
results. Program fees and  commitment length will also vary 
dependent on the amount that your debt   can be reduced and your ability
 to save funds. </p>
        <p> Disclaimer: This website is not intended to, nor does it, 
provide   legal advice, nor is it intended to be a substitute for legal 
advice. If   you need legal advice you must consult with a licensed 
attorney.   Services are available to Canadian residents only and may 
not be   available in all provinces. Please read and understand contract
 terms   &amp; conditions prior to enrollment. If you have any questions
   regarding this advertisement, please email support@debtadvisors22.ca. </p>
        <p> *You must have a minimum of $10,000 in unsecured debt to apply. </p>
        <p>We have taken every effort to design our website to be 
useful,   informative, helpful, honest and fun. Hopefully we have 
accomplished   that - and would ask that you let us know if you'd like 
to see   improvements or changes that would make it even easier for you 
to find   the information you need and want. All we ask is that you 
agree to abide   by the following Terms and Conditions. Take a few 
minutes to look them   over because by using our site you automatically 
agree to them.   Naturally, if you don't agree, please do not use the 
site. We reserve   the right to make any modifications that we deem 
necessary at any time.   Please continue to check these terms to see 
what those changes may be!   Your continued use of the 
Debt Advisors website means that you accept those   changes.</p>
        <p><strong>Restrictions on Use of Our Online Materials</strong></p>
        <p>All Online Materials on the Debt Advisors site, 
including, without   limitation, text, software, names, logos, 
trademarks, service marks,   trade names, images, photos, illustrations,
 audio clips, video clips,   and music are copyrighted intellectual 
property. All usage rights are   owned and controlled by 
Debt Advisors. You, the visitor, may download   Online Materials 
for non-commercial, personal use only provided you 1)   retain all 
copyright, trademark and propriety notices, 2) you make no   
modifications to the materials, 3) you do not use the materials in a   
manner that suggests an association with any of our products, services, 
  events or brands, and 4) you do not download quantities of materials 
to a   database, server, or personal computer for reuse for commercial  
 purposes. You may not, however, copy, reproduce, republish, upload,   
post, transmit or distribute Online Materials in any way or for any   
other purpose unless you get our written permission first. Neither may  
 you add, delete, distort or misrepresent any content on the 
Debt Advisors   site. Any attempts to modify any Online Material, 
or to defeat or   circumvent our security features are prohibited. 
Everything you   download, any software, plus all files, all images 
incorporated in or   generated by the software, and all data 
accompanying it, is considered   licensed to you by Debt Advisors 
or third-party licensers for your   personal, non-commercial home use 
only. We do not transfer title of the   software to you. That means that
 we retain full and complete title to   the software and to all of the 
associated intellectual-property rights.   You're not allowed to 
redistribute or sell the material or to   reverse-engineer, disassemble 
or otherwise convert it to any other form   that people can use.</p>
        <p><strong>Submitting Your Online Material to Us</strong></p>
        <p>All remarks, suggestions, ideas, graphics, comments, or other
   information that you send to Debt Advisors through our site 
(other than   information we promise to protect under our privacy policy
 becomes and   remains our property, even if this agreement is later 
terminated. That   means that we don't have to treat any such submission
 as confidential.   You can't sue us for using ideas you submit. If we 
use them, or anything   like them, we don't have to pay you or anyone 
else for them. We will   have the exclusive ownership of all present and
 future rights to   submissions of any kind. We can use them for any 
purpose we deem   appropriate to our Debt Advisors mission, 
without compensating you or   anyone else for them. You acknowledge that
 you are responsible for any   submission you make. This means that you 
(and not we) have full   responsibility for the message, including its 
legality, reliability,   appropriateness, originality, and copyright.</p>

        <p><strong>Limitation of Liability</strong></p>
        <p>Debt Advisors WILL NOT BE LIABLE FOR ANY DAMAGES OR 
LOSS THAT   ACCOMPANY OR RESULT FROM YOUR USE OF ANY OF ITS SITE. 
THESE INCLUDE (BUT   ARE NOT LIMITED TO) DAMAGES OR LOSS CAUSED BY 
ANY: USE OF (OR   INABILITY TO USE) THE SITE USE OF (OR INABILITY TO 
USE) ANY SITE TO   WHICH YOU HYPERLINK FROM OUR SITE FAILURE OF OUR SITE
 TO PERFORM IN THE   MANNER YOU EXPECTED OR DESIRED ERROR ON OUR SITE 
OMISSION ON OUR SITE   INTERRUPTION OF AVAILABILITY OF OUR SITE DEFECT 
ON OUR SITE DELAY IN   OPERATION OR TRANSMISSION OF OUR SITE COMPUTER 
VIRUS OR LINE FAILURE   PLEASE NOTE THAT WE ARE NOT LIABLE FOR ANY 
DAMAGES, INCLUDING: DAMAGES   INTENDED TO COMPENSATE SOMEONE DIRECTLY 
FOR A LOSS OR  DAMAGES   REASONABLY EXPECTED TO RESULT FROM A LOSS 
(KNOWN IN LEGAL   TERMS AS "CONSEQUENTIAL DAMAGES.") OTHER 
MISCELLANEOUS DAMAGES AND   EXPENSES RESULTING DIRECTLY FROM A LOSS 
(KNOWN IN LEGAL TERMS   AS "INCIDENTAL DAMAGES.") WE ARE NOT 
LIABLE EVEN IF WE'VE BEEN NEGLIGENT   OR IF OUR AUTHORIZED 
REPRESENTATIVE HAS BEEN ADVISED OF THE POSSIBILITY   OF SUCH DAMAGES OR 
BOTH. EXCEPTION: CERTAIN STATE LAWS MAY NOT ALLOW US   TO LIMIT OR 
EXCLUDE LIABILITY FOR THESE "INCIDENTAL" OR "CONSEQUENTIAL"   DAMAGES. 
IF YOU LIVE IN ONE OF THOSE STATES, THE ABOVE LIMITATION   OBVIOUSLY 
WOULD NOT APPLY WHICH WOULD MEAN THAT YOU MIGHT HAVE THE RIGHT   TO 
RECOVER THESE TYPES OF DAMAGES. HOWEVER, IN ANY EVENT, OUR LIABILITY   
TO YOU FOR ALL LOSSES, DAMAGES, ICAURIES, AND CLAIMS OF ANY AND EVERY   
KIND (WHETHER THE DAMAGES ARE CLAIMED UNDER THE TERMS OF A CONTRACT, OR 
  CLAIMED TO BE CAUSED BY NEGLIGENCE OR OTHER WRONGFUL CONDUCT, OR 
THEY'RE   CLAIMED UNDER ANY OTHER LEGAL THEORY) WILL NOT BE GREATER THAN
 THE   AMOUNT YOU PAID IF ANYTHING TO ACCESS OUR SITE.</p>
        <p><strong>Links to Other Site</strong></p>
        <p>We sometimes provide referrals to and links to other World 
Wide   websites from our site. Such a link should not be seen as an   
endorsement, approval or agreement with any information or resources   
offered at sites you can access through our site. If in doubt, always   
check the Uniform Resource Locator (URL) address provided in your WWW   
browser to see if you are still in a Debt Advisors-operated site 
or have   moved to another site. Debt Advisors is not responsible 
for the content or   practices of third party sites that may be linked 
to our site. When   Debt Advisors provides links or references to 
other websites, no inference   or assumption should be made and no 
representation should be inferred   that Debt Advisors is 
connected with, operates or controls these websites.   Any approved link
 must not represent in any way, either explicitly or by   implication, 
that you have received the endorsement, sponsorship or   support of any 
Debt Advisors site or endorsement, sponsorship or support of   
Debt Advisors, including its respective employees, agents or 
directors.</p>
        <p><strong>Termination of This Agreement</strong></p>
        <p>This agreement is effective until terminated by either party.
 You may   terminate this agreement at any time, by destroying all 
materials   obtained from all Debt Advisors websites, along with 
all related   documentation and all copies and installations. 
Debt Advisors may terminate   this agreement at any time and 
without notice to you, if, in its sole   judgment, you breach any term 
or condition of this agreement. Upon   termination, you must destroy all
 materials. In addition, by providing   material on our website, we do 
not in any way promise that the materials   will remain available to 
you. And Debt Advisors is entitled to terminate   all or any part 
of any of its website without notice to you.</p>
        <p>Jurisdiction and Other Points to Consider If you use our site
 from   locations outside of Canada, you are responsible for compliance 
with any   applicable local laws. These Terms of Use shall be governed 
by,   construed and enforced in accordance with the laws of the British 
  Columba, Canada, as it is applied to agreements entered into and to be
   performed entirely within such jurisdiction. To the extent you have 
in   any manner violated or threatened to violate Debt Advisors 
and/or its   affiliates' intellectual property rights, 
Debt Advisors and/or its   affiliates may seek injunctive or other
 appropriate relief in any court   in the province of British Columbia, 
Canada, and you consent to   exclusive jurisdiction and venue in such 
courts. <br>
        </p>
        <p>For more information, contact us at 
support@debtadvisors22.ca. Mailing address: 4720 Kingsway, Suite 2600 
Burnaby, British Columbia, V5H 4N2. </p>


	
	</td>
	</tr>
  </tbody>
</table>
</center>


</body></html>